- name: install python dependency packages 
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
    - PyMySQL
    - cryptography

- name: install Mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present
  
- name: start and enable the mysql service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: connect to mysql server
  community.mysql.mysql_info: #mysql -h <host-address> -u root -p<password>
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql.gsdevops.online
  register: mysql_info
  ignore_errors: true    # ignore error and proceeds to next task

- name: print the mysql_info output
  ansible.builtin.debug:
    msg: "MySQL info: {{ mysql_info }}"

- name: setup root password
  ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_root_password }} "
  when: mysql_info.failed is true
